### ISSUE TITLE
Separation of concern 

### ISSUE THREAD

**Issue by TheCollinsByte** [paradigm-lab/dotfiles#2]
Using different directories for dotfiles configuration rather than using the default `dotfiles` within the project.

**Comment by mattjquinn** [comment]
It's certainly possible. But this is a challenge I'll let you think about and solve.

**Comment by TheCollinsByte** [comment]
Worry out, I am going to complete my exam today then I will jump on it as soon as possible.

**Comment by TheCollinsByte** [comment]
Got a new PR in the repo for branch named [collin-separation-of-concern](https://github.com/paradigm-lab/dotfiles/tree/collin-separation-of-concern)

**Comment by mattjquinn** [comment]
> Got a new PR in the repo for branch named [collin-separation-of-concern](https://github.com/paradigm-lab/dotfiles/tree/collin-separation-of-concern)

I see the branch but there's no PR for it, if you create the PR I will add review comments to it.

**Comment by TheCollinsByte** [comment]
PR created https://github.com/paradigm-lab/dotfiles/pull/3
